image: hashicorp/terraform:full
pipelines:
    default:
        - step:
            name: 'Deploy ECS Cluster'
            script:
                - echo "Deploy Infraestructure with Terraform..."
                - terraform init
                - terraform validate
                - terraform plan
                - terraform apply -input=false -auto-approve
